<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@0.0.5 static/assets/characters/Stag.gltf --types --shadows --draco --transform --S
-->
<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, Three, type Props, type Events, type Slots } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group>;

	export const ref = new Group();
	export let bones:
		| {
				IKBackLegL: THREE.Bone;
				IKFrontLegL: THREE.Bone;
				IKBackLegR: THREE.Bone;
				IKFrontLegR: THREE.Bone;
				Body: THREE.Bone;
		  }
		| undefined = undefined;

	type ActionName =
		| 'Attack_Headbutt'
		| 'Attack_Kick'
		| 'Death'
		| 'Eating'
		| 'Gallop'
		| 'Gallop_Jump'
		| 'Idle'
		| 'Idle_2'
		| 'Idle_Headlow'
		| 'Idle_HitReact1'
		| 'Idle_HitReact2'
		| 'Jump_toIdle'
		| 'Walk';
	type GLTFResult = {
		nodes: {
			Stag_Horns: THREE.Mesh;
			Cube: THREE.SkinnedMesh;
			Cube_1: THREE.SkinnedMesh;
			Cube_2: THREE.SkinnedMesh;
			Cube_3: THREE.SkinnedMesh;
			Cube_4: THREE.SkinnedMesh;
			Body: THREE.Bone;
			IKBackLegL: THREE.Bone;
			IKFrontLegL: THREE.Bone;
			IKBackLegR: THREE.Bone;
			IKFrontLegR: THREE.Bone;
		};
		materials: {
			['Material.001']: THREE.MeshStandardMaterial;
			Material: THREE.MeshStandardMaterial;
			['Material.001']: THREE.MeshStandardMaterial;
			['Material.003']: THREE.MeshStandardMaterial;
			['Material.010']: THREE.MeshStandardMaterial;
			['Material.011']: THREE.MeshStandardMaterial;
		};
	};

	const { gltf } = useGltf<GLTFResult>('/Stag-transformed.glb', { useDraco: true });
	// const { gltf } = useGltf<GLTFResult>('/assets/characters/Stag.gltf', { useDraco: true });
	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref.children[0]);

	$: {
		if ($gltf) {
			bones = {
				IKBackLegL: $gltf.nodes.IKBackLegL,
				IKFrontLegL: $gltf.nodes.IKFrontLegL,
				IKBackLegR: $gltf.nodes.IKBackLegR,
				IKFrontLegR: $gltf.nodes.IKFrontLegR,
				Body: $gltf.nodes.Body
			};
		}
	}
</script>

{#if $gltf}
	<Three type={ref} {...$$restProps}>
		<T.Group name="Scene">
			<T.Group name="AnimalArmature">
				<Three type={$gltf.nodes.Body} />
				<Three type={$gltf.nodes.IKBackLegL} />
				<Three type={$gltf.nodes.IKFrontLegL} />
				<Three type={$gltf.nodes.IKBackLegR} />
				<Three type={$gltf.nodes.IKFrontLegR} />
				<T.Group name="Stag">
					<T.SkinnedMesh
						name="Cube"
						castShadow
						receiveShadow
						geometry={$gltf.nodes.Cube.geometry}
						material={$gltf.materials.Material}
						skeleton={$gltf.nodes.Cube.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube_1"
						castShadow
						receiveShadow
						geometry={$gltf.nodes.Cube_1.geometry}
						material={$gltf.materials['Material.001']}
						skeleton={$gltf.nodes.Cube_1.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube_2"
						castShadow
						receiveShadow
						geometry={$gltf.nodes.Cube_2.geometry}
						material={$gltf.materials['Material.003']}
						skeleton={$gltf.nodes.Cube_2.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube_3"
						castShadow
						receiveShadow
						geometry={$gltf.nodes.Cube_3.geometry}
						material={$gltf.materials['Material.010']}
						skeleton={$gltf.nodes.Cube_3.skeleton}
					/>
					<T.SkinnedMesh
						name="Cube_4"
						castShadow
						receiveShadow
						geometry={$gltf.nodes.Cube_4.geometry}
						material={$gltf.materials['Material.011']}
						skeleton={$gltf.nodes.Cube_4.skeleton}
					/>
				</T.Group>
			</T.Group>
		</T.Group>

		<slot {ref} />
	</Three>
{/if}
